14-rails-forms-associations/pet-sanctuary/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Users
  # get "/users", to: "users#index", as: "users"
  # get "/users/:id", to: "users#show", as: "user"
  # delete "/users/:id", to: "users#destroy"
  resources :users, only: [:index, :show, :destroy]

  resources :pets
end

14-rails-forms-associations/pet-sanctuary/app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

end

14-rails-forms-associations/pet-sanctuary/app/models/user.rb
class User < ApplicationRecord
  # If an instance of user is destroyed, also destroy every instance of pet that belongs to them
  has_many :pets, dependent: :destroy
end

14-rails-forms-associations/pet-sanctuary/app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    # Create pet here
    @pet = Pet.create(pet_params)
    redirect_to pets_path
  end

  def update
    @pet = Pet.find(params[:id])
    # Update pet here
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id)
  end

  def destroy
    Pet.destroy(params[:id])
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :user_id)
  end

end

14-rails-forms-associations/pet-sanctuary/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])

    redirect_to pets_path
  end
end

14-rails-forms-associations/pet-sanctuary/app/helpers/pets_helper.rb
module PetsHelper
end

14-rails-forms-associations/pet-sanctuary/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <!-- Creates a select drop-down menu and options. The arguments passed to it (in order) correspond to: the name of the key that will be created in the params hash to represent the value of the user's selection (in this case user_id), what the dropdown will be populated with (in this case, all the instances of User), the value that will be submitted from the selected option (in this case, the selected user's id) and the value that will be shown in the dropdown in the view to show the user which option they are selecting (in this case, the username of each user) -->
  <%= f.label :user %>
  <%= f.collection_select :user_id, User.all, :id, :username %>

  <%= f.submit %>
<% end %>

14-rails-forms-associations/pet-sanctuary/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @pet.name %></h2>
<h3>belongs to <%= link_to @pet.user.username, user_path(@pet.user) %></h3>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>