16-travelatr-review/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :bloggers, only: [:show, :new]

  # Blogger Routes
  get '/bloggers', to: 'bloggers#index', as: 'bloggers'
  get '/bloggers/new', to: 'bloggers#new', as: 'new_blogger'
  post '/bloggers', to: 'bloggers#create'
  get '/bloggers/:id', to: 'bloggers#show', as: 'blogger'

  # Post Routes
  resources :posts, only: [:new, :index, :create, :show]
  post '/posts/:id', to: 'posts#like', as: "like"
  
  # Destination Routes
  resources :destinations, only: [:show]
end

16-travelatr-review/app/models/blogger.rb
class Blogger < ApplicationRecord
  has_many :posts
  has_many :destinations, through: :posts

  validates :name, uniqueness: true
  validates :age, numericality: { greater_than: 0 }
  validates :bio, length: { minimum: 30 }

  def total_likes
    likes = self.posts.map { |post| post.likes }
    likes.sum
  end

  def featured_post
    self.posts.max_by {|post| post.likes }
  end
end

16-travelatr-review/app/models/destination.rb
class Destination < ApplicationRecord
  has_many :posts
  has_many :bloggers, through: :posts

  def latest_posts
    self.posts.last(5)
  end

  def featured_post
    self.posts.max_by { |post| post.likes }
  end

  def unique_bloggers
    self.bloggers.uniq
  end

  def average_age_of_bloggers
    ages = self.unique_bloggers.map { |blogger| blogger.age }
    ages.sum / ages.length
  end
end

16-travelatr-review/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blogger
  belongs_to :destination

  validates :title, presence: true
  validates :content, length: { minimum: 100 }

  def increase_like
    self.update(likes: self.likes + 1)
  end
end

16-travelatr-review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

16-travelatr-review/app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController

  def new
    @blogger = Blogger.new
  end

  def create
    @blogger = Blogger.create(blogger_params)

    @blogger = Blogger.new(blogger_params)
    @blogger.save

    if @blogger.valid?
      redirect_to blogger_path(@blogger)
    else
      render :new
    end
  end

  def show
    @blogger = Blogger.find(params[:id])
  end

  private

  def blogger_params
    params.require(:blogger).permit(:name, :bio, :age)
  end
end

16-travelatr-review/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def show
    @destination = Destination.find(params[:id])
  end

end

16-travelatr-review/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @bloggers = Blogger.all
    @destinations = Destination.all
  end

  def create
    @post = Post.create(post_params)

    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:id])
  end

  def like
    @post = Post.find(params[:id])
    
    @post.destroy

    redirect_to post_path(@post)
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :content, :blogger_id, :destination_id)
  end

end

16-travelatr-review/app/helpers/bloggers_helper.rb
module BloggersHelper
end

16-travelatr-review/app/helpers/destinations_helper.rb
module DestinationsHelper
end

16-travelatr-review/app/helpers/posts_helper.rb
module PostsHelper
end

16-travelatr-review/app/views/bloggers/new.html.erb
<h1>Create New Blogger</h1>

<% if @blogger.errors %>
  <ul>
  <% @blogger.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @blogger do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <br><br>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br><br>
  <%= f.submit %>
<% end %>

16-travelatr-review/app/views/bloggers/show.html.erb
<h1><%= @blogger.name %></h1>
<h2><%= @blogger.age %></h2>

<p>BIO: <%= @blogger.bio %></p>

<h5>Total likes: <%= @blogger.total_likes %></h5>
<%= link_to @blogger.featured_post, post_path(@blogger.featured_post), method: :delete%>

16-travelatr-review/app/views/destinations/show.html.erb
<h1><%= @destination.name %></h1>
<h2><%= @destination.country %></h2>

<h5>Avg age: <%= @destination.average_age_of_bloggers %></h5>

<h4>Featured Post:</h4>
<%= link_to @destination.featured_post.title, post_path(@destination.featured_post) %>

<h4>Latest Posts:</h4>
<ul>
<% @destination.latest_posts.each do |post| %>
  <li><%= post.title %></li>
<% end %>
</ul>

16-travelatr-review/app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br><br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br><br>
  <%= f.label :blogger %>
  <%= f.collection_select :blogger_id, @bloggers, :id, :name %>
  <br><br>
  <%= f.label :destination %>
  <%= f.collection_select :destination_id, @destinations, :id, :name %>
  <br><br>
  <%= f.submit %>
<% end %>

16-travelatr-review/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h4>Number of likes: </h4>
<%= @post.likes %>

<br><br>
<%= link_to "Like this post!", like_path(@post), method: :post %>