13-rails-forms-rest/pet-sanctuary/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Seven RESTful routes, with prefixes
  # get "/pets", to: "pets#index", as: "pets"
  # get "/pets/:id", to: "pets#show", as: "pet"
  # get "/pets/new", to: "pets#new", as: "new_pet"
  # get "/pets/:id/edit", to: "pets#edit", as: "edit_pet"
  # post "/pets", to: "pets#create"
  # patch "/pets/:id", to: "pets#update"
  # delete "/pets/:id", to: "pets#destroy"

  # Resources - this will create all seven RESTful routes for pets for us, with the appropriate prefixes
  resources :pets
end

13-rails-forms-rest/pet-sanctuary/app/models/pet.rb
class Pet < ApplicationRecord
end

13-rails-forms-rest/pet-sanctuary/app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    # Create a new instance of pet to fill in with values for our new form
    @pet = Pet.new
  end

  def edit
    # Find an existing instance of pet to update with new values for our edit form
    @pet = Pet.find(params[:id])
  end

  def create
    # Create pet here
    @pet = Pet.create(pet_params) # Create our pet using our permitted parameters
    # Redirect to the show page for this instance of pet
    redirect_to @pet
  end

  def update
    @pet = Pet.find(params[:id])
    # Update pet here
    @pet.update(pet_params)  # Update our pet using our permitted parameters
    # Redirect to thee show page for this instance of pet
    redirect_to @pet
  end

  def destroy
    Pet.destroy(params[:id])
    redirect_to pets_path
  end

  # All methods declared after this line will be private - private methods cannot be called outside of the class they are defined in
  private

  # Strong params - Define the parameters that we will accept for our resource. In this case, when a user submits a request to us, the only parameters for a pet we will allow are name and age
  def pet_params
    params.require(:pet).permit(:name, :age)
  end


end

13-rails-forms-rest/pet-sanctuary/app/views/pets/_form.html.erb
<!-- This ActionView::Helper will create a form for us. The form_for helper is specifically for instances of one our models. This also allows us to make a form that works to both create or update an instance, depening on whether the form is being rendered from the new or edit route respectively -->
<%= form_for(@pet) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.submit %>
<% end %>

13-rails-forms-rest/pet-sanctuary/app/views/pets/_old_form.html.erb
<!-- This ActionView::Helper will create a form for us. It includes an authenticity token which is necessary to submit requests via a form in Rails. We should only use this form_tag helper for forms that aren't going to create or update an instance of one of our models e.g. a user login form -->
<%= form_tag pets_path do %>
  <!-- We can use specific ActionView::Helper methods for each type of input field. The :pet, :name and :pet, :age syntax means that the name and age keys will be placed inside a nested pet hash within params i.e. params => { pet => { name: , age: }}  -->
  <%= label :pet, :name %>
  <%= text_field :pet, :name %>

  <%= label :pet, :age %>
  <%= number_field :pet, :age %>

  <%= submit_tag "Save Pet" %>
<% end %>

13-rails-forms-rest/pet-sanctuary/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>
<!-- Render our form partial. We just say "form", but Rails is actually going to look for a file called "_form.html.erb" - make sure to put an underscore (_) before the names of your partial files -->
<!-- We pass it an instance of pet as an argument so that it knows whether submitting the form should create (if @pet is an empty instance) or update (if @pet is an existing pet from our database)-->
<%= render "form", pet: @pet %>


<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

13-rails-forms-rest/pet-sanctuary/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= link_to pet.name, pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <!-- Override the method for this anchor tag. Now, when we click on this link, it will send a delete request, allowing it to match our destroy route. -->
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

13-rails-forms-rest/pet-sanctuary/app/views/pets/new.html.erb
<h1>New Pet</h1>
<!-- Render our form partial. We just say "form", but Rails is actually going to look for a file called "_form.html.erb" - make sure to put an underscore (_) before the names of your partial files -->
<!-- We pass it an instance of pet as an argument so that it knows whether submitting the form should create (if @pet is an empty instance) or update (if @pet is an existing pet from our database)-->
<%= render "form", pet: @pet %>



<%= link_to 'Back', pets_path %>

13-rails-forms-rest/pet-sanctuary/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @pet.name %></h2>
<p><%= @pet.age %></p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>